# Subject: Data Science Foundation

## Session 13 - Correlation in Python.

### Assignment 1 -  Calculating Correlation for pandas Dataframe "Titanic"


- Considering the Correlation analysis presented in Demo 1 develop a new one for the data set “Titanic”. 
- Select the variables most appropriate and justify your option.
- Commit scripts in your GitHub account. You should export your your solution code (.ipynb notebook) and push it to your repository “DataScienceFoundations”.
- The following are the tasks that should complete and synchronize with your repository “DataScienceFoundations” until November 23. Please notice that this task will not be graded, however it’s important that you correctly understand and complete them in order to be sure that you won’t have problems with further assignments.

Guidelines:
- Clone the Git repository to get an initial code: 
https://github.com/FGutierresBTS/BTS_MasterInBigData.git
- Once you downloaded the repository to your local file system, go to the folder “BTS_MasterInBigData/ Session_13_DSF”. 
- Copy the folder “Session_13_DSF” into your local folder “DataScienceFoundations”. 
- In the folder “Session_13_DSF” you will see the files called: 
    -	BTS_DataScienceFoundations_Session13_Correlation_Individual_assignment.ipynb.
    -   "1_titanic_dataset.csv" (note: this dataset must be pre-processed).
- Import these files into Jupyter Notebook using the “Upload” button. 
- Open the imported script and put your code inside the notebook. 
- Export your Assignment *.ipynb notebook and push it to your repository “DataScienceFoundations”.

In [56]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder  
%matplotlib inline
df=pd.read_csv("1_titanic_dataset.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [57]:
df.drop(['PassengerId'], axis=1).corr().style.format('{:.2}').background_gradient(cmap=plt.get_cmap('PuBu'), axis=1)

In [58]:
corrs = pd.DataFrame(df.corr()['Survived'][2:])
corrs.sort_values(by='Survived').style.format('{:.2}').background_gradient(cmap=plt.get_cmap('PuBu'))

Most importatn variable in Titanic dataset is "Survived", it shows wherer passenger survived or not. Observing on the variable correlations with other items, we can say that only two of them ar correlated (Pcalss and Fare). Pclass has negative correlation, wchich according to data means that person in lower class had less probability of survival. Contrary Fare has possitive correlation, higher price person payed, higher was survival probability.

As we can see from results above, pandas corr() function couldn't consider gender and Embarked variables because they are objects, not numericals. In order to have more precies correlation alayses, first we need to transform those variables into numericals.

In [60]:
le = LabelEncoder()
df['Sex'] = le.fit_transform(df['Sex'])

In [61]:
df['Embarked'] = le.fit_transform(df['Embarked'])

TypeError: '>' not supported between instances of 'str' and 'float'

In [70]:
def score_to_numeric(x):
    if x=='S':
        return 3
    if x=='C':
        return 2
    if x=='Q':
        return 1
    
df['Embarked'] = df['Embarked'].apply(score_to_numeric)

In [71]:
df.drop(['PassengerId'], axis=1).corr().style.format('{:.2}').background_gradient(cmap=plt.get_cmap('PuBu'), axis=1)

In [73]:
corrs_new = pd.DataFrame(df.corr()['Survived'][2:])
corrs_new.sort_values(by='Survived').style.format('{:.2}').background_gradient(cmap=plt.get_cmap('PuBu'))

As we expected, Ses variable is the highest correlated variable to survival, with negative value meaning that men had less chanse of survivial. We also transormed Embarked variable to numerical but it has not significant correlation to survival variable.